dell-home brother printer

diff --git a/nodes/dell-home.yml b/nodes/dell-home.yml
--- a/nodes/dell-home.yml
+++ b/nodes/dell-home.yml
@@ -42,8 +42,8 @@
       # command: bash -c "/usr/sbin/alsactl"
       # not sure if this should be with store or init
     - command: /usr/sbin/alsactl
-        args:
-          creates: /var/lib/alsa/asound.state
+      args:
+        creates: /var/lib/alsa/asound.state
       notify: reboot
 
     #####
@@ -183,28 +183,49 @@
     #####
     # Support bridge addif for qemu
     # tunctl from uml-utilities only needed for permissions, not strictly needed
+    - apt: name=uml-utilities
     - copy:
         dest: /etc/qemu-ifup
         mode: 0755
         content: |
-          #!/bin/sh
+          #!/bin/sh -x
           # deployed by ansible
-          set -x
+          echo "i am $(whoami)"
           switch=br0
           if [ -n "$1" ];then
+              # has to be run as root...
               # tunctl -u `whoami` -t $1
               ip link set $1 up
               sleep 0.5s
               brctl addif $switch $1
               exit 0
           else
+              ECHO "Error: no interface specified"
+              exit 1
+          fi
+
+    - copy:
+        dest: /etc/qemu-ifdown
+        mode: 0755
+        content: |
+          #!/bin/sh -x
+          # deployed by ansible
+          switch=br0
+          if [ -n "$1" ];then
+              # permissions...
+              brctl delif $switch $1
+              ip link delete $1
+              exit 0
+          else
               echo "Error: no interface specified"
               exit 1
           fi
 
+
     #####
     - apt: name=dnsutils
     - apt: name=ffmpeg
+    - apt: name=a2ps
 
 
     # local changes not in dotfiles for .bashrc
@@ -214,6 +235,30 @@
         content: |
           # ansible test
 
+    #####
+    - apt: name=cups
+    - service: name=cups state=started
+
+    - shell: lpstat -p | grep -q Brother
+      register: have_printer
+      ignore_errors: yes
+      changed_when: "have_printer.rc != 0"
+
+    # TODO a more relative path?
+    - copy: src=../roles/common/files/BRHL16_2_GPL.ppd dest=/tmp
+
+      # brother.localnet
+      # 192.168.43.15
+    - shell: |
+        # install
+        lpadmin \
+          -p 'Brother' \
+          -v 'socket://brother:9100' \
+          -P '/tmp/BRHL16_2_GPL.ppd' \
+          -E
+        # set default
+        lpadmin -d Brother
+      when: "have_printer.rc != 0"
 
 
   handlers:
