dell-work reorg dnsmasq and support kvm

diff --git a/nodes/dell-work.yml b/nodes/dell-work.yml
--- a/nodes/dell-work.yml
+++ b/nodes/dell-work.yml
@@ -153,7 +153,7 @@
     # so make local dns authoritative
     - apt: name=dnsmasq
     - copy:
-        dest: /etc/dnsmasq.d/container-dns
+        dest: /etc/dnsmasq.d/localnet
         content: |
           # deployed by ansible!
           interface=br0
@@ -163,16 +163,24 @@
           server=131.217.0.19
           server=144.6.0.19
           expand-hosts
-          domain=container
-          dhcp-range=br0,10.1.1.10,10.1.1.20,4h
-          dhcp-host=00:01:04:1b:2C:0A,wordpress,10.1.1.11
-          dhcp-host=00:01:04:1b:2C:19,geoserver,10.1.1.12
+          domain=localnet
+          dhcp-range=br0,10.1.1.10,10.1.1.30,4h
+
+          # systemd containers
+          dhcp-host=00:01:04:1b:2C:0A,wordpress,10.1.1.10
+          dhcp-host=00:01:04:1b:2C:0B,geoserver,10.1.1.11
+          dhcp-host=00:01:04:1b:2C:1A,jessie,10.1.1.12
+          dhcp-host=00:01:04:1b:2C:1B,geonetwork2,10.1.1.13
           dhcp-host=00:01:04:1b:2C:1C,portal,10.1.1.14
-          dhcp-host=00:01:04:1b:2C:1F,geonetwork3,10.1.1.15
+          dhcp-host=00:01:04:1b:2C:1D,aatams,10.1.1.15
           dhcp-host=00:01:04:1b:2C:1E,rev-proxy,10.1.1.16
-          dhcp-host=00:01:04:1b:2C:1D,aatams,10.1.1.17
-          dhcp-host=00:01:04:1b:2C:1B,geonetwork2,10.1.1.18
-          dhcp-host=00:01:04:1b:2C:1A,jessie,10.1.1.19
+          dhcp-host=00:01:04:1b:2C:1F,geonetwork3,10.1.1.17
+
+          # kvm guests
+          dhcp-host=00:01:04:1b:2C:2A,5-aws-syd,10.1.1.18
+          dhcp-host=00:01:04:1b:2C:2B,6-aws-syd,10.1.1.19
+          dhcp-host=00:01:04:1b:2C:2C,win7,10.1.1.20
+
       notify: restart-dnsmasq
 
     # TODO - this doesn't clear the file first
@@ -234,6 +242,54 @@
     # - include: "./roles/common/tasks/jdk.yml"
     - include: ../roles/misc/tasks/grails-1.3.7.yml
     - include: ../roles/misc/tasks/intellij.yml
+
+
+    #####
+    # Support bridge addif for qemu
+    # tunctl from uml-utilities only needed for permissions, not strictly needed
+    - apt: name=qemu-kvm
+    - apt: name=uml-utilities
+
+    - copy:
+        dest: /etc/qemu-ifup
+        mode: 0755
+        content: |
+          #!/bin/sh -x
+          # deployed by ansible
+          echo "i am $(whoami)"
+          switch=br0
+          if [ -n "$1" ];then
+              # has to be run as root...
+              # tunctl -u `whoami` -t $1
+              ip link set $1 up
+              sleep 0.5s
+              brctl addif $switch $1
+              exit 0
+          else
+              ECHO "Error: no interface specified"
+              exit 1
+          fi
+
+    - copy:
+        dest: /etc/qemu-ifdown
+        mode: 0755
+        content: |
+          #!/bin/sh -x
+          # deployed by ansible
+          switch=br0
+          if [ -n "$1" ];then
+              # permissions...
+              brctl delif $switch $1
+              ip link delete $1
+              exit 0
+          else
+              echo "Error: no interface specified"
+              exit 1
+          fi
+
+
+
+
 
   # TODO maybe make handlers explicit
   handlers:
